[metadata]
creation_date = "2023/10/11"
integration = ["github"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"
updated_date = "2023/10/11"
bypass_bbr_timing = true

[rule]
author = ["Elastic"]
description = """
A new GitHub Organization member added in the last 7 days has interacted with a repository.
"""
from = "now-9m"
index = ["logs-github.audit-*"]
language = "eql"
license = "Elastic License v2"
name = "Repo Interaction From a Newly Added Member"
risk_score = 21
rule_id = "d4fcb2c3-c55e-4485-ad29-e75727b241c5"
severity = "low"
tags = ["Domain: Cloud",
        "Use Case: Threat Detection",
        "Tactic: Execution",
        "Rule Type: BBR",
        "Data Source: Github"
        ]
timestamp_override = "event.ingested"
type = "eql"
building_block_type = "default"

query = '''
sequence by github.org with maxspan=7d
[configuration where event.dataset == "github.audit" and event.action == "org.add_member"] by user.target.name
[configuration where event.dataset == "github.audit" and github.category == "repo"] by user.name
'''

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1648"
name = "Serverless Execution"
reference = "https://attack.mitre.org/techniques/T1648/"


[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
