[metadata]
creation_date = "2023/10/11"
integration = ["github"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"
updated_date = "2023/10/11"
bypass_bbr_timing = true

[rule]
author = ["Elastic"]
description = """
Detects a high number of repo clone events originating from a single personal access token within a 5 minute interval.
"""
from = "now-9m"
index = ["logs-github.audit-*"]
language = "eql"
license = "Elastic License v2"
name = "High Number of Cloned GitHub Repos From PAT"
risk_score = 21
rule_id = "fb0afac5-bbd6-49b0-b4f8-44e5381e1587"
severity = "low"
tags = ["Domain: Cloud",
        "Use Case: Threat Detection",
        "Tactic: Execution",
        "Rule Type: BBR",
        "Data Source: Github"
        ]
timestamp_override = "event.ingested"
type = "eql"
building_block_type = "default"

query = '''
sequence by github.hashed_token with maxspan=5m
 [configuration where event.dataset == "github.audit" and event.action == "git.clone" 
 and github.programmatic_access_type in ("OAuth access token", "Fine-grained personal access token")] with runs=25
'''

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1648"
name = "Serverless Execution"
reference = "https://attack.mitre.org/techniques/T1648/"


[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
