[metadata]
creation_date = "2023/10/11"
integration = ["github"]
maturity = "production"
min_stack_comments = "Multiple field support in the New Terms rule type was added in Elastic 8.6"
min_stack_version = "8.6.0"
updated_date = "2023/10/11"
bypass_bbr_timing = true

[rule]
author = ["Elastic"]
description = """
Detects a new IP address used for a GitHub user not previously seen in the last 7 days.
"""
from = "now-9m"
index = ["logs-github.audit-*"]
language = "kuery"
license = "Elastic License v2"
name = "New IP Address For GitHub User"
risk_score = 21
rule_id = "3af4cb9b-973f-4c54-be2b-7623c0e21b2b"
severity = "low"
tags = ["Domain: Cloud",
        "Use Case: Threat Detection",
        "Tactic: Initial Access",
        "Rule Type: BBR",
        "Data Source: Github"
        ]
timestamp_override = "event.ingested"
type = "new_terms"
building_block_type = "default"

query = '''
    event.dataset: "github.audit" and event.category : "configuration" and
    github.actor_ip:* and user.name:*
'''

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1078"
name = "Valid Accounts"
reference = "https://attack.mitre.org/techniques/T1078/"
[[rule.threat.technique.subtechnique]]
id = "T1078.004"
name = "Cloud Accounts"
reference = "https://attack.mitre.org/techniques/T1078/004/"

[rule.threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"

[rule.new_terms]
field = "new_terms_fields"
value = ["github.actor_ip", "user.name"]

[[rule.new_terms.history_window_start]]
field = "history_window_start"
value = "now-7d"